# Use official Python image as base
FROM python:3.11-slim

# Set working directory
WORKDIR /testapp

# Copy requirements file
COPY ./test/requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY ./test .

# Set default command (adjust as needed)
CMD ["python", "testapp.py"]